# https://golangci-lint.run/usage/configuration/

run:
  timeout: 2m
  # skip test files
  tests: false
  skip-dirs:
    - prow/scripts/resources/autobumper # not needed for this job
linters:
  disable-all: true
  enable:
    - deadcode
    - exportloopref
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    # - revive # replaces golint
