- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    mountPath: /etc/untrusted-workload-kubeconfig
    name: untrusted-workload-kubeconfig
    readOnly: true
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    mountPath: /etc/trusted-workload-kubeconfig
    name: trusted-workload-kubeconfig
    readOnly: true
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: untrusted-workload-kubeconfig
    secret:
      defaultMode: 420
      secretName: untrusted-workload-kubeconfig
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: trusted-workload-kubeconfig
    secret:
      defaultMode: 420
      secretName: trusted-workload-kubeconfig
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: KUBECONFIG
    value: "/etc/untrusted-workload-kubeconfig/config:/etc/trusted-workload-kubeconfig/config"