plugins:
  kyma-project:
    plugins:
      - cat
      - trigger
      - assign
      - wip
      - lgtm
      - hold
      - label
      - yuks
      - dog
      - size
      - shrug
      - invalidcommitmsg
      - help
  kyma-project/test-infra:
    plugins:
      - config-updater
      - approve
      - blunderbuss
      - verify-owners
      - owners-label
      - milestone
      - override
      - retitle
      - pony
      - lifecycle
      - transfer-issue
      - project
  kyma-incubator:
    plugins:
      - cat
      - trigger
      - assign
      - wip
      - lgtm
      - hold
      - label
      - yuks
      - dog
      - size
      - shrug
      - invalidcommitmsg
      - help

external_plugins:
  kyma-project/test-infra:
    - name: needs-tws
      events:
        - pull_request
        - pull_request_review

config_updater:
  maps:
    prow/jobs/**/*.yaml:
      name: job-config
      gzip: true
    prow/config.yaml:
      name: config
    prow/branchprotector-config.yaml:
      name: branchprotector-config
    prow/plugins.yaml:
      name: plugins
    prow/labels.yaml:
      name: label-config
      clusters:
        trusted-workload:
          - default
    prow/cluster/static-files/*:
      name: static-files

triggers:
  - repos:
      - kyma-project
      - kyma-incubator
    trusted_apps:
      - dependabot
    only_org_members: true
    ignore_ok_to_test: true

lgtm:
  - repos:
      - kyma-project
      - kyma-incubator
    review_acts_as_lgtm: true

label:
  additional_labels:
    - tide/merge-method-merge
    - tide/merge-method-rebase
    - tide/merge-method-squash
    - Epic

size:
  s:   10
  m:   30
  l:   100
  xl:  500
  xxl: 1000

blunderbuss:
  max_request_count: 2
  use_status_availability: true
  ignore_drafts: true

approve:
  - repos:
      - kubernetes/test-infra
    require_self_approval: false
    ignore_review_state: false

# https://github.com/kubernetes/test-infra/blob/master/prow/plugins/plugin-config-documented.yaml#L506
project_config:
  project_org_configs:
    kyma-project:
      # curl -H "Authorization: Token <token>" "https://api.github.com/orgs/kyma-project/teams?page=N"
      org_maintainers_team_id: 5611091 # project-maintainers

# https://github.com/kubernetes/test-infra/blob/master/prow/plugins/plugin-config-documented.yaml#L541
repo_milestone:
  # Default maintainer
  # the list of different maintainers can be defined per org/repo
  '':
    # curl -H "Authorization: Token <token>" "https://api.github.com/orgs/kyma-project/teams?page=N"
    maintainers_id: 5611091
    maintainers_team: project-maintainers

